### ISSUE TITLE
Script crashing on channel thumbnails

### ISSUE THREAD

**Issue by bigdav1178** [fHDHR/fHDHR_Locast#121]
I've begun testing your fHDHR scripts (Locast, PlutoTV and XUMO), and found that the Locast script is failing on thumbnails:

Loading fHDHR v0.4.6-beta
Loading fHDHR_web v0.4.0-beta
Loading Origin Service: fHDHR_Locast v0.5.0-beta
Loading Configuration File: ./config.ini
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, origin, alternative_epg))
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/cli/run.py", line 108, in main
    return start(args, script_dir, fHDHR_web, origin, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/cli/run.py", line 96, in start
    return run(settings, logger, db, script_dir, fHDHR_web, origin, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/cli/run.py", line 42, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, origin, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/__init__.py", line 32, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.originwrapper, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/device/__init__.py", line 13, in __init__
    self.channels = Channels(fhdhr, originwrapper)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/device/channels/__init__.py", line 25, in __init__
    self.get_channels()
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/device/channels/__init__.py", line 77, in get_channels
    channel_dict_list = self.origin.get_channels()
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/originwrapper/__init__.py", line 54, in get_channels
    return self.channels.get_channels()
  File "/opt/fHDHR/fHDHR_Locast/origin/origin_channels.py", line 31, in get_channels
    "thumbnail": station_item["logo226Url"]
KeyError: 'logo226Url'

I am able to workaround the issue, and successfully run the script, by commenting out the "thumbnail" declaration (Line 31) from origin_channels.py .

            clean_station_item = {
                                 "name": station_item["name"],
                                 "id": station_item["id"]#,
                                 # "thumbnail": station_item["logo226Url"]
                                 }

**Comment by deathbybandaid** [comment]
What DMA?

**Comment by bigdav1178** [comment]
Philadelphia market

**Comment by deathbybandaid** [comment]
@bigdav1178 
do me a favor and test #122 after deleting your database file (stored in your cache directory)

**Comment by bigdav1178** [comment]
That fixed it; thanks!
