### ISSUE TITLE
Script crashing on channel thumbnails (revisited)

### ISSUE THREAD

**Issue by bigdav1178** [fHDHR/fHDHR_Locast#129]
Looks like I spoke too soon on this one; I was accidentally running the script out of my (fixed) backup directory when I said it was working. When I tried running the latest release this morning, I had the issue occur again:

Traceback (most recent call last):
  File "/opt/fHDHR/fHDHR_Locast/main.py", line 20, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, origin, alternative_epg))
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/cli/run.py", line 108, in main
    return start(args, script_dir, fHDHR_web, origin, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/cli/run.py", line 96, in start
    return run(settings, logger, db, script_dir, fHDHR_web, origin, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/cli/run.py", line 42, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, origin, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/__init__.py", line 32, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.originwrapper, alternative_epg)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/device/__init__.py", line 13, in __init__
    self.channels = Channels(fhdhr, originwrapper)
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/device/channels/__init__.py", line 25, in __init__
    self.get_channels()
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/device/channels/__init__.py", line 83, in get_channels
    channel_dict_list = self.origin.get_channels()
  File "/opt/fHDHR/fHDHR_Locast/fHDHR/originwrapper/__init__.py", line 37, in get_channels
    return self.channels.get_channels()
  File "/opt/fHDHR/fHDHR_Locast/origin/origin_channels.py", line 33, in get_channels
    thumbnail = station_item[thumb_opt]
KeyError: 'logo226Url'

Changing line 33 of the origin_channels.py file to "except KeyError:" (rather than "except TypeError:") resolves the problem.

BTW, great work on this project!

**Comment by deathbybandaid** [comment]
I'll get that fixed in my next push

**Comment by deathbybandaid** [comment]
Just confirm the new push fixes this, and close it if it does?

**Comment by bigdav1178** [comment]
I can confirm that fixed it. Thanks!
