### ISSUE TITLE
Orange Pi One+ (Arm64): locast exited with code 1

### ISSUE THREAD

**Issue by rj45jack** [fHDHR/fHDHR_Locast#182]
Hi,

I am getting this error when running on an Orange Pi One+ with Armbian.

```
locast     | fHDHR - INFO - Logging into Locast using username null...
locast     | Loading fHDHR v0.6.0-beta
locast     | Loading fHDHR_web v0.8.0-beta
locast     | Loading Origin Service: fHDHR_Locast v0.5.0-beta
locast     | Loading Configuration File: /app/config/config.ini
locast     | Warning: Do not run fHDHR with root privileges.
locast     | Traceback (most recent call last):
locast     |   File "/app/main.py", line 18, in <module>
locast     |     sys.exit(run.main(SCRIPT_DIR, fHDHR_web, origin, alternative_epg))
locast     |   File "/app/fHDHR/cli/run.py", line 92, in main
locast     |     returned_code = start(args, script_dir, fHDHR_web, origin, alternative_epg)
locast     |   File "/app/fHDHR/cli/run.py", line 79, in start
locast     |     return run(settings, logger, db, script_dir, fHDHR_web, origin, alternative_epg)
locast     |   File "/app/fHDHR/cli/run.py", line 35, in run
locast     |     fhdhr = fHDHR_OBJ(settings, logger, db, origin, alternative_epg)
locast     |   File "/app/fHDHR/__init__.py", line 32, in __init__
locast     |     self.originwrapper = OriginServiceWrapper(self.fhdhr, origin)
locast     |   File "/app/fHDHR/originwrapper/__init__.py", line 16, in __init__
locast     |     self.setup()
locast     |   File "/app/fHDHR/originwrapper/__init__.py", line 21, in setup
locast     |     self.originservice = self.origin.OriginService(self.fhdhr)
locast     |   File "/app/origin/origin_service.py", line 25, in __init__
locast     |     self.login()
locast     |   File "/app/origin/origin_service.py", line 29, in login
locast     |     self.token = self.get_token()
locast     |   File "/app/origin/origin_service.py", line 58, in get_token
locast     |     loginRes = loginReq.json()
locast     |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
locast     |     return complexjson.loads(self.text, **kwargs)
locast     |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
locast     |     return _default_decoder.decode(s)
locast     |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
locast     |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
locast     |   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
locast     |     raise JSONDecodeError("Expecting value", s, err.value) from None
locast     | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
locast exited with code 1
```

I am already running fHDHR_PlutoTV without issue.

**Comment by deathbybandaid** [comment]
Can't right now, but I'll add some handling for that in the morning.

In the meantime, verify your credentials are correct, and let me know if you have special characters in your config

**Comment by rj45jack** [comment]
Thanks.

The username/PW have to line up with a system account? Or is it for the webgui?

No special characters in the config.

**Comment by deathbybandaid** [comment]
This would be your account with Locast

**Comment by deathbybandaid** [comment]
#185 adds some error handling, which won't fix your problem, but will now error out the correct way

**Comment by deathbybandaid** [comment]
@rj45jack any updates on your end?

**Comment by rj45jack** [comment]
Consider it resolved. I rebuilt my VM and reran the docker build without error. I'm unsure what the underlying issue was at this point.

**Comment by deathbybandaid** [comment]
Awesome!
