### ISSUE TITLE
Windows multiprocessing spawn error

### ISSUE THREAD

**Issue by tharris9d** [fHDHR/fHDHR_Locast#53]
I am using the latest Master beta.. I am getting EOFError: Ran out of input. I deleted the cache, and ran from the command-line when the service didn't work.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by deathbybandaid** [comment]
Any more traceback abve that?

I'm currently mid-rewrite of core again.... new version should be out later this week.

Any more detail on this issue would be helpful

**Comment by tharris9d** [comment]
Here is the info..

Loading fHDHR v0.3.0-beta
Validating CLI Argument
Loading Configuration File: c:\code\fhdhr_locast_1\config.ini
Verifying Configuration settings.
UUID read as: xr76213...
Cache set to C:\code\fhdhr_locast_1\data\cache
Server is set to run on  127.0.0.1:5004
Logging into Locast using username xxxxxx...
User Info obtained.
User didDonate: True
User donationExpire: 2020-11-11 18:00:49
Getting location via IP Address.
Got external IP 137.25.43.76.
Got location as Los Angeles - DMA 803 - Lat\Lon 34.1121\-118.2594
Locast Login Success
fHDHR-Locast is now running!
Starting fHDHR Web Interface
Loading Previously Saved Channel Numbers.
Found 54 channels for Locast
Saving Channel Numbers.
SSDP server Starting
Starting EPG thread...
Updating locast EPG cache file.
FROM CACHE: C:\code\fhdhr_locast_1\data\cache\origin\web_cache\2020-11-03
FROM CACHE: C:\code\fhdhr_locast_1\data\cache\origin\web_cache\2020-11-04
FROM CACHE: C:\code\fhdhr_locast_1\data\cache\origin\web_cache\2020-11-05
FROM CACHE: C:\code\fhdhr_locast_1\data\cache\origin\web_cache\2020-11-06
FROM CACHE: C:\code\fhdhr_locast_1\data\cache\origin\web_cache\2020-11-07
FROM CACHE: C:\code\fhdhr_locast_1\data\cache\origin\web_cache\2020-11-08
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Wrote locast EPG cache file.

**Comment by deathbybandaid** [comment]
That's odd, it seems like the data being pulled from locast api is corrupt somehow?

Does everything else seem to work besides channel guide?

Also, try setting the `[fhdhf]epg_method` to `zap2it`, and let me know if you get the same issue.

**Comment by tharris9d** [comment]
With epg_method = zap2it

Loading fHDHR v0.3.0-beta
Validating CLI Argument
Loading Configuration File: c:\code\fhdhr_locast_1\config.ini
Verifying Configuration settings.
UUID read as: xr76213...
Cache set to C:\code\fhdhr_locast_1\data\cache
Server is set to run on  127.0.0.1:5004
Logging into Locast using username tom.harris@9di.com...
User Info obtained.
User didDonate: True
User donationExpire: 2020-11-11 18:00:49
Getting location via IP Address.
Got external IP 37.235.108.43.
Got location as Los Angeles - DMA 803 - Lat\Lon 34.0522\-118.2437
Locast Login Success
fHDHR-Locast is now running!
Starting fHDHR Web Interface
Loading Previously Saved Channel Numbers.
Found 54 channels for Locast
Saving Channel Numbers.
SSDP server Starting
Starting EPG thread...
Updating zap2it EPG cache file.
Zap2it postalcode not set, attempting to retrieve.
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604469600&Activity_ID=1&FromPage=TV%2520Guide
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604491200&Activity_ID=1&FromPage=TV%2520Guide
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604512800&Activity_ID=1&FromPage=TV%2520Guide
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604534400&Activity_ID=1&FromPage=TV%2520Guide
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604556000&Activity_ID=1&FromPage=TV%2520Guide
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604577600&Activity_ID=1&FromPage=TV%2520Guide
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604599200&Activity_ID=1&FromPage=TV%2520Guide
Fetching:   https://tvlistings.zap2it.com/api/grid?aid=gapzap&country=USA&device=-&headendId=lineupId&isoverride=true&languagecode=en&pref=m%2Cp&timespan=6&timezone=None&userId=-&postalCode=90053&lineupId=USA---DEFAULT&time=1604620800&Activity_ID=1&FromPage=TV%2520Guide

**Comment by deathbybandaid** [comment]
I'm polishing the final touches for v0.4.0, I'll be pushing that in the next couple days, and we'll revisit this then

In the meantime, you could try some fancy git voodoo to go back to a commit that worked for you.

**Comment by tharris9d** [comment]
I look forward to v0.4.0. I rolled back to the previous version and it is working again. Thanks for your work on this.

**Comment by deathbybandaid** [comment]
The new version sees some very important changes. The script and web interface will be able to be run even with the Backend login credentials (locast) being incorrect.

It will also feature logging levels.

**Comment by deathbybandaid** [comment]
@tharris9d I'm still doing some testing locally, but if you want to test deathbybandaid/fHDHR_Locast dev branch, I believe it to be almost ready to publish.

RN, I'm working out a quirk of the PlutoTV version, that will have effect on all the repos

**Comment by tharris9d** [comment]
Awesome. I will test it out.

**Comment by deathbybandaid** [comment]
testing out asynchio instead of multiprocessing. Initial testing looks to be better at being threadsafe, with faster access to the backend from the http server

**Comment by deathbybandaid** [comment]
@tharris9d New Version pushed, please give it a try, and also test out the webUI

**Comment by tharris9d** [comment]
Can't wait to test....I will report back soon. Thanks...

**Comment by deathbybandaid** [comment]
Migrated from Other Thread

Here is my error: I tried to update my config.ini based on the example so some settings may be wrong. Could you upload a base config.ini example with just what is need to run it successfully. 

````
Loading fHDHR v0.4.0-beta
Loading Configuration File: c:\code\fhdhr_locast_1\config.ini
HTTP Server Starting
Traceback (most recent call last):
  File "C:\code\fhdhr_locast_1\main.py", line 17, in <module>
    sys.exit(run.main(SCRIPT_DIR))
  File "C:\code\fhdhr_locast_1\fHDHR\cli\run.py", line 89, in main
    return start(args, script_dir)
  File "C:\code\fhdhr_locast_1\fHDHR\cli\run.py", line 79, in start
    return run(settings, logger, db)
  File "C:\code\fhdhr_locast_1\fHDHR\cli\run.py", line 44, in run
    fhdhr_web.start()
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'gevent._gevent_clocal.local' object
Press any key to continue . . . Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect
````

**Comment by tharris9d** [comment]
I just downloaded and ran the latest code update from today
I am getting new errors. Let me know what I'm missing. The last working code for me is ver .0.2.9.
Thanks, 
Tom

Loading fHDHR v0.4.0-beta
Loading Configuration File: c:\code\fhdhr_locast_3\config.ini
HTTP Server Starting
Traceback (most recent call last):
  File "C:\code\fhdhr_locast_3\main.py", line 17, in <module>
    sys.exit(run.main(SCRIPT_DIR))
  File "C:\code\fhdhr_locast_3\fHDHR\cli\run.py", line 93, in main
    return start(args, script_dir)
  File "C:\code\fhdhr_locast_3\fHDHR\cli\run.py", line 83, in start
    return run(settings, logger, db)
  File "C:\code\fhdhr_locast_3\fHDHR\cli\run.py", line 48, in run
    fhdhr_web.start()
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'NoneType' object is not callable
Press any key to continue . . . Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied

**Comment by deathbybandaid** [comment]
I think I'm goingbto have to drop windows support then. Sorry.

**Comment by deathbybandaid** [comment]
One thing you can try is switch the stream method to direct

**Comment by deathbybandaid** [comment]
Windows and `multiprocessing.Process` don't get along well.

PRs are welcome to ensure Windows support.

**Comment by deathbybandaid** [comment]
Can you try a python earlier than 3.7.2, just a suggestion from googling the problem

**Comment by deathbybandaid** [comment]
I'll see what I can find out about this tomorrow, but forums and stackoverflow don't seem to have good answers for windows.

**Comment by deathbybandaid** [comment]
Went to do some testing for this, and another required package `pycrypto` is failing to install.

Closing this issue, as I can't support running on Windows at this time.
