### ISSUE TITLE
0.4.0 error in SSDP data on startup M-SEARCH

### ISSUE THREAD

**Issue by crackers8199** [fHDHR/fHDHR_Locast#57]
```
Loading fHDHR v0.4.0-beta
Loading Configuration File: /app/config/config.ini
HTTP Server Starting
SSDP Server Starting
EPG Update Starting
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/fHDHR/device/ssdp.py", line 190, in run
    self.on_recv(data, address)
  File "/app/fHDHR/device/ssdp.py", line 111, in on_recv
    header, payload = data.decode().split('\r\n\r\n')[:2]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by tharris9d** [comment]
Here is my error: I tried to update my config.ini based on the example so some settings may be wrong. Could you upload a base config.ini example with just what is need to run it successfully. 

Loading fHDHR v0.4.0-beta
Loading Configuration File: c:\code\fhdhr_locast_1\config.ini
HTTP Server Starting
Traceback (most recent call last):
  File "C:\code\fhdhr_locast_1\main.py", line 17, in <module>
    sys.exit(run.main(SCRIPT_DIR))
  File "C:\code\fhdhr_locast_1\fHDHR\cli\run.py", line 89, in main
    return start(args, script_dir)
  File "C:\code\fhdhr_locast_1\fHDHR\cli\run.py", line 79, in start
    return run(settings, logger, db)
  File "C:\code\fhdhr_locast_1\fHDHR\cli\run.py", line 44, in run
    fhdhr_web.start()
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'gevent._gevent_clocal.local' object
Press any key to continue . . . Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect

**Comment by deathbybandaid** [comment]
@tharris9d I'm starting to think your issues are Windows related. If so, I may have to drop support for Windows

**Comment by crackers8199** [comment]
she just saw it. she said the spinning buffering circle came up, and then when it came back the video and audio were out of sync (which is similar to what i've seen in channels, but without the buffering - there it just skips backwards and then never recovers). plex at least recovered after a second or two, and the a/v resumed sync.

**Comment by deathbybandaid** [comment]
@tharris9d can you migrate your comments to your other issue thread so I can think clearly?
