### ISSUE TITLE
error on first stream after docker container boot

### ISSUE THREAD

**Issue by crackers8199** [fHDHR/fHDHR_Locast#64]
the first stream after booting the docker container throws up this error in the logs (when using direct stream type):

```
fHDHR - INFO - Tuner #1 Acquired.
fHDHR - ERROR - Exception on /auto/v5.1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 567, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 385, in read
    return self._sslobj.read(nbytes, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2623)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.locastnet.org', port=443): Max retries exceeded with url: /api/watch/station/1079/33.707/-117.245 (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2623)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR/http/watch/auto.py", line 14, in __call__
    return self.get(channel, *args)
  File "/app/fHDHR/http/watch/auto.py", line 63, in get
    stream_args = self.fhdhr.device.tuners.get_stream_info(stream_args)
  File "/app/fHDHR/device/tuners/__init__.py", line 74, in get_stream_info
    stream_args["channelUri"] = self.channels.get_channel_stream(str(stream_args["channel"]))
  File "/app/fHDHR/device/channels.py", line 100, in get_channel_stream
    streamlist, caching = self.origin.get_channel_stream(chandict, self.list)
  File "/app/fHDHR/origin/__init__.py", line 58, in get_channel_stream
    return self.channels.get_channel_stream(chandict, allchandict)
  File "/app/fHDHR/origin/origin_channels.py", line 57, in get_channel_stream
    videoUrlReq = self.fhdhr.web.session.get(videoUrl, headers=videoUrl_headers)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.locastnet.org', port=443): Max retries exceeded with url: /api/watch/station/1079/33.707/-117.245 (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2623)')))
192.168.88.165 - - [2020-11-13 17:24:33] "GET /auto/v5.1? HTTP/1.1" 500 426 0.131032
fHDHR - ERROR - Tuner #1 is not available.
```

at this point, tuner 1 is stuck on "acquired" until i close it from the UI (which i can't do if i'm at the point where the streams page doesn't work, although i haven't seen that yet...) 

all streams after this seem to be fine.

i will create a new issue for this, since it's really unrelated to this one.

**Comment by deathbybandaid** [comment]
I've seen this error before, normally a reboot fixes it

**Comment by deathbybandaid** [comment]
Closing until reproduced
